// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH3PKHzTKylzgU6rbEQm_n1FksJUxL3TY',
    appId: '1:305013403016:web:eb9919b9fc003d0c08de3d',
    messagingSenderId: '305013403016',
    projectId: 'windwavewing',
    authDomain: 'windwavewing.firebaseapp.com',
    storageBucket: 'windwavewing.firebasestorage.app',
    measurementId: 'G-EJFH856S9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2pn2OwGpwsMDDQcQYj-D8YvPkFO8kmA',
    appId: '1:305013403016:android:0c7359684f6f153908de3d',
    messagingSenderId: '305013403016',
    projectId: 'windwavewing',
    storageBucket: 'windwavewing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvQXLOTeLWCiZMC5kgVOvMRPxKSbZI0as',
    appId: '1:305013403016:ios:2c0870052a3ecba108de3d',
    messagingSenderId: '305013403016',
    projectId: 'windwavewing',
    storageBucket: 'windwavewing.firebasestorage.app',
    iosBundleId: 'com.example.tfgClimaMalaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvQXLOTeLWCiZMC5kgVOvMRPxKSbZI0as',
    appId: '1:305013403016:ios:2c0870052a3ecba108de3d',
    messagingSenderId: '305013403016',
    projectId: 'windwavewing',
    storageBucket: 'windwavewing.firebasestorage.app',
    iosBundleId: 'com.example.tfgClimaMalaga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH3PKHzTKylzgU6rbEQm_n1FksJUxL3TY',
    appId: '1:305013403016:web:8b9f04febb6f3b5408de3d',
    messagingSenderId: '305013403016',
    projectId: 'windwavewing',
    authDomain: 'windwavewing.firebaseapp.com',
    storageBucket: 'windwavewing.firebasestorage.app',
    measurementId: 'G-2Z9RRDW8VV',
  );
}
